sudo: false
language: node_js
node_js:
- '0.12'
env:
  global:
  - DEPLOY_BRANCH=master
cache:
  directories:
  - node_modules
before_install:
- chmod +x ./.build_scripts/lint.sh
before_script:
- "./.build_scripts/lint.sh"
script:
- npm test
- npm run build
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: AKIAIHACHLPCT2PIL4TA
  secret_access_key:
    secure: NfTKYFZe8Yk1EcGTWT4qcljdbSJ3LEqEkWbehChFSaJgKp64mMkZ9C9ur0DKtqm9C4Ruw9KxRV7uYRQvxqdyqg+39IYP5ZeoR1OPnymghRxWDONkWs+2257uhzw4gKYXygWmfRUMTTpQ5N0bM4Q7xWwzwPXIr67xnM9XsXjnFrqB9zum1SjpybjJC+zS4ecKoco1bFvlBf04RfC2smW7pJNDoRy34hA+rt39mayzPhELuqC5k4W/M2ymqpBDFJxnca70zHUczJzI1enzLciNM8lPPRAVCA7yNf/xJBcWK9prhGfJtoT5Cb0UYOSeOPb38QTCa+mmc43OK/62fpzyJUjrvFZNU+Yr1+IsBX6QBC6S7Acb/obTY2sjADR/GrywruCclPbp71Gx+wu8Q5tk4UGlHhyNi7k5zEecNK8M2kdAfjPVHRVN9CJXMhlJLT+6sM3xFAvWRt9csagP8ZeU5iTIlxWXbzoEvrbNNOS3bPH0ulWnMcfer5W5oL6o/kNkXrxQnfAf4pHLyqGQas4X6/QBR100ZwtRl45U0m8n1jnB3eqT8gCAkCIg/xwxg0HwZJCHPsk9MdXMh0qB+zxagrZLjKGorXbRbCnNQlwZpAoG1geNIabyBESo2VVTl/5vdMyDPycObZkWxw9YuNMztq7PKrpnswu/FEO6qV5MJv8=
  bucket: labs.openaq.org
  local-dir: dist
  upload-dir: aq-viz
  acl: public_read
  on:
    repo: openaq/aq-viz
    branch: ${DEPLOY_BRANCH}
