sudo: false
language: node_js
node_js:
  - "0.12"

env:
  global:
  - GH_REF=github.com/openaq/aq-viz.git
  - DEPLOY_BRANCH=master
  - secure: "lpx9wBQSyHOfRlA0WTBolmBz6AqcoUISVKUkG5gSqBJJMYLpp83KaVuIog9bWJXU5HQc4QXswujPdjh2muCUbLESzyDKUlJ7PucH1rfndxX6c50F+hIHjl3jzBe8LkK2tnvqp7i0ceCq1lgVrei5Dc54dy5OIjulxYSPBF9bRJ/Rzsdsaa1/JBC/V95I17fvBKWg/x0fq9Qep0F2b0KNdnvAivpb4H2hEnOENX5cCyWn9Bd3mXmtDtUY3vuYis0mjpVdwo5c6hOmAuGRL0OMKYGWvAjn3VY8vmet4KJCUlNnJiLtfpjxEMd32gyBg9LXVOrbBsSg39OwhPLcbjN1swNHDGqWJy6iLUTPRLrgGqV8XQmYjR+1ck3LXaFgs5oyN/r0zaw12d+IDZZAKTPoLrk/9poR9jEsqugOxqVh+4t9Qbj6f4mbhZNqgY97XQxYmkHI24cpnNRX0WH25MsvgvrBot0yoyz1yq22+Wsb2AkM7RQAMdhqsquyR9JcH1rttBwtI99/p+7QxHAyrTieuciKajwvBx+zXA4pivHsFVZ8Ton6Lu7/wlKZINHrCmrzzArp8FMAbcQ9p9XF0ykX9BNAnFJqonXT8QqPghFl5/P33yNKu5515LtgpwwQsJ4PjTGlTg7jYstY48k+RMyimr2d/CqQUKh0FFWtFHMj/9A="

cache:
  directories:
    - node_modules

before_install:
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh

before_script:
- ./.build_scripts/lint.sh

script:
- npm test
- npm run build

deploy:
- provider: script
- skip_cleanup: true
- script: .build_scripts/deploy.sh
